nodeLinker: pnp
enableGlobalCache: false
npmRegistryServer: "https://registry.npmjs.org"
yarnPath: .yarn/releases/yarn-4.5.3.cjs

packageExtensions:
  '@vitejs/plugin-react@*':
    peerDependencies:
      'vite': '*'
  'eslint-config-airbnb@*':
    peerDependencies:
      'eslint-plugin-import': '*'
      'eslint-plugin-jsx-a11y': '*'
      'eslint-plugin-react': '*'