export const countryNameToCode: Record<string, string> = {
    "Papua New Guinea": "PG",
    "Greenland": "GL",
    "Iceland": "IS",
    "Canada": "CA",
    "Algeria": "DZ",
    "Benin": "BJ",
    "Burkina Faso": "BF",
    "Ghana": "GH",
    "Cote d'Ivoire": "CI",
    "Nigeria": "NG",
    "Niger": "NE",
    "Tunisia": "TN",
    "Togo": "TG",
    "Belgium": "BE",
    "Germany": "DE",
    "Estonia": "EE",
    "Finland": "FI",
    "United Kingdom": "GB",
    "Guernsey": "GG",
    "Jersey": "JE",
    "Isle of Man": "IM",
    "Falkland Islands": "FK",
    "Netherlands": "NL",
    "Ireland": "IE",
    "Denmark": "DK",
    "Faroe Islands": "FO",
    "Luxembourg": "LU",
    "Norway": "NO",
    "Poland": "PL",
    "Sweden": "SE",
    "South Africa": "ZA",
    "Botswana": "BW",
    "Congo (Brazzaville)": "CG",
    "Congo (Kinshasa)": "CD",
    "Swaziland": "SZ",
    "Central African Republic": "CF",
    "Equatorial Guinea": "GQ",
    "Saint Helena": "SH",
    "Mauritius": "MU",
    "British Indian Ocean Territory": "IO",
    "Cameroon": "CM",
    "Zambia": "ZM",
    "Comoros": "KM",
    "Mayotte": "YT",
    "Reunion": "RE",
    "Madagascar": "MG",
    "Angola": "AO",
    "Gabon": "GA",
    "Sao Tome and Principe": "ST",
    "Mozambique": "MZ",
    "Seychelles": "SC",
    "Chad": "TD",
    "Zimbabwe": "ZW",
    "Malawi": "MW",
    "Lesotho": "LS",
    "Mali": "ML",
    "Gambia": "GM",
    "Spain": "ES",
    "Sierra Leone": "SL",
    "Guinea-Bissau": "GW",
    "Liberia": "LR",
    "Morocco": "MA",
    "Senegal": "SN",
    "Mauritania": "MR",
    "Guinea": "GN",
    "Cape Verde": "CV",
    "Ethiopia": "ET",
    "Burundi": "BI",
    "Somalia": "SO",
    "Egypt": "EG",
    "Kenya": "KE",
    "Libya": "LY",
    "Rwanda": "RW",
    "Sudan": "SD",
    "South Sudan": "SS",
    "Tanzania": "TZ",
    "Uganda": "UG",
    "Albania": "AL",
    "Bulgaria": "BG",
    "Cyprus": "CY",
    "Croatia": "HR",
    "France": "FR",
    "Saint Pierre and Miquelon": "PM",
    "Greece": "GR",
    "Hungary": "HU",
    "Italy": "IT",
    "Slovenia": "SI",
    "Czech Republic": "CZ",
    "Israel": "IL",
    "Malta": "MT",
    "Austria": "AT",
    "Portugal": "PT",
    "Bosnia and Herzegovina": "BA",
    "Romania": "RO",
    "Switzerland": "CH",
    "Turkey": "TR",
    "Moldova": "MD",
    "Macedonia": "MK",
    "Gibraltar": "GI",
    "Serbia": "RS",
    "Montenegro": "ME",
    "Slovakia": "SK",
    "Turks and Caicos Islands": "TC",
    "Dominican Republic": "DO",
    "Guatemala": "GT",
    "Honduras": "HN",
    "Jamaica": "JM",
    "Mexico": "MX",
    "Nicaragua": "NI",
    "Panama": "PA",
    "Costa Rica": "CR",
    "El Salvador": "SV",
    "Haiti": "HT",
    "Cuba": "CU",
    "Cayman Islands": "KY",
    "Bahamas": "BS",
    "Belize": "BZ",
    "Cook Islands": "CK",
    "Fiji": "FJ",
    "Tonga": "TO",
    "Kiribati": "KI",
    "Wallis and Futuna": "WF",
    "Samoa": "WS",
    "American Samoa": "AS",
    "French Polynesia": "PF",
    "Vanuatu": "VU",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Antarctica": "AQ",
    "Afghanistan": "AF",
    "Bahrain": "BH",
    "Saudi Arabia": "SA",
    "Iran": "IR",
    "Jordan": "JO",
    "West Bank": "PS",
    "Kuwait": "KW",
    "Lebanon": "LB",
    "United Arab Emirates": "AE",
    "Oman": "OM",
    "Pakistan": "PK",
    "Iraq": "IQ",
    "Syria": "SY",
    "Qatar": "QA",
    "Northern Mariana Islands": "MP",
    "Guam": "GU",
    "Marshall Islands": "MH",
    "Midway Islands": "US", // 미국 영토로 대체
    "Micronesia": "FM",
    "Palau": "PW",
    "Taiwan": "TW",
    "Japan": "JP",
    "South Korea": "KR",
    "Philippines": "PH",
    "Argentina": "AR",
    "Brazil": "BR",
    "Chile": "CL",
    "Ecuador": "EC",
    "Paraguay": "PY",
    "Colombia": "CO",
    "Bolivia": "BO",
    "Suriname": "SR",
    "French Guiana": "GF",
    "Peru": "PE",
    "Uruguay": "UY",
    "Venezuela": "VE",
    "Guyana": "GY",
    "Antigua and Barbuda": "AG",
    "Barbados": "BB",
    "Dominica": "DM",
    "Martinique": "MQ",
    "Guadeloupe": "GP",
    "Grenada": "GD",
    "Virgin Islands": "VI",
    "Puerto Rico": "PR",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Aruba": "AW",
    "Netherlands Antilles": "BQ",
    "Anguilla": "AI",
    "Trinidad and Tobago": "TT",
    "British Virgin Islands": "VG",
    "Saint Vincent and the Grenadines": "VC",
    "Kazakhstan": "KZ",
    "Kyrgyzstan": "KG",
    "Azerbaijan": "AZ",
    "Russia": "RU",
    "Ukraine": "UA",
    "Belarus": "BY",
    "Turkmenistan": "TM",
    "Tajikistan": "TJ",
    "Uzbekistan": "UZ",
    "India": "IN",
    "Sri Lanka": "LK",
    "Cambodia": "KH",
    "Bangladesh": "BD",
    "Hong Kong": "HK",
    "Laos": "LA",
    "Macau": "MO",
    "Nepal": "NP",
    "Bhutan": "BT",
    "Maldives": "MV",
    "Thailand": "TH",
    "Vietnam": "VN",
    "Burma": "MM",
    "Indonesia": "ID",
    "Malaysia": "MY",
    "Brunei": "BN",
    "East Timor": "TL",
    "Singapore": "SG",
    "Australia": "AU",
    "Christmas Island": "CX",
    "Norfolk Island": "NF",
    "China": "CN",
    "North Korea": "KP",
    "Mongolia": "MN",
    "United States": "US",
    "Latvia": "LV",
    "Lithuania": "LT",
    "Armenia": "AM",
    "Eritrea": "ER",
    "Palestine": "PS",
    "Georgia": "GE",
    "Yemen": "YE",
    "Bermuda": "BM",
    "Solomon Islands": "SB",
    "Nauru": "NR",
    "Tuvalu": "TV",
    "Namibia": "NA",
    "Djibouti": "DJ",
    "Montserrat": "MS",
    "Johnston Atoll": "-", // 미국 영토로 대체
    "Western Sahara": "EH",
    "Niue": "NU",
    "Cocos (Keeling) Islands": "CC",
    "Myanmar": "MM",
    "Svalbard": "SJ",
    "Wake Island": "-" // 미국 영토로 대체
};